all:
	g++ -std=c++0x -g ejercicio2.cpp -o ejercicio2
	g++ -std=c++0x -g tests-generator.cpp -o tests-generator
	g++ -std=c++0x -g ejercicio2-timer.cpp -o ejercicio2-timer
clean:
	rm  -f *.o ejercicio2
