all:
	g++ -std=c++0x -g ejercicio2.cpp -o ejercicio2
	g++ -std=c++0x -g ejercicio3.cpp -o ejercicio3
	g++ -std=c++0x -g ejercicio3-listas.cpp -o ejercicio3-listas
	g++ -std=c++0x -g ejercicio4.cpp -o ejercicio4
	g++ -std=c++0x -g ejercicio5.cpp -o ejercicio5
clean:
	rm  -f *.o ejercicio2 ejercicio3 ejercicio3-listas ejercicio4 ejercicio5
